### ISSUE TITLE
Should we need to break contigs before running endhic?

### ISSUE THREAD

**Issue by xiekunwhy** [fanagislab/EndHiC#1]
Hi,

Should we need to break contigs (break potential errors) before running endhic? How to break them if we need to do that or why we don't need to do that?

Best,
Kun

**Comment by kingforest93** [comment]
Yes, `endhic` is designed for scaffolding large and accurate contigs. If there are assembly errors (usually misjoins) in the large (> 1-Mb) contigs, currently `endhic` does not correct them in the following steps.

**Comment by kingforest93** [comment]
Yes, `endhic` is designed for scaffolding large and accurate contigs. If there are assembly errors (usually misjoins) in the large (> 1-Mb) contigs, currently `endhic` does not correct them in the following steps.
Drawing a Hi-C heatmap of the potential error-assembled contigs can help you find the position to split.
