### ISSUE TITLE
How to resolve Multi-HiC libraries

### ISSUE THREAD

**Issue by kedduck** [fanagislab/EndHiC#7]
Dear Developer

Thanks for your good tool

I want  to try the tool, but I have two HiC libraries.

Should I merge the fastq before running HiC-Pro?

Expect for your reply

**Comment by fanagislab** [comment]
Yes, I think you can do it.




***@***.***
 
From: keduck
Date: 2022-04-13 10:51
To: fanagislab/EndHiC
CC: Subscribed
Subject: [fanagislab/EndHiC] How to resolve Multi-HiC libraries (Issue #7)
Dear Developer
Thanks for your good tool
I want to try the tool, but I have two HiC libraries.
Should I merge the fastq before running HiC-Pro?
Expect for your reply

**Comment by kedduck** [comment]
Thank you !
